test:
  adapter: postgresql
  encoding: unicode
  database: tomato_time_api_test

development:
  adapter: postgresql
  encoding: unicode
  database: tomato_time_api_development

production:
  adapter: postgresql
  encoding: unicode
  database: tomato_time_api
  url: <%= ENV['DATABASE_URL'] %>
