development:
  adapter: postgresql
  encoding: unicode
  database: tomato_time_api
  pool: 2
  username: nancylee
  password: your_password
  
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
