test:
  adapter: postgresql
  encoding: unicode
  database: tomato_time_api_test

development:
  adapter: postgresql
  encoding: unicode
  database: tomato_time_api_development

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
