test:
  adapter: postgresql
  encoding: unicode
  database: tomato_time_api

development:
  adapter: postgresql
  encoding: unicode
  database: tomato_time_api

production:
  adapter: postgresql
  encoding: unicode
