test:
  adapter: postgresql
  encoding: unicode
  database: tomato_time_api_test

development:
  adapter: postgresql
  encoding: unicode
  database: tomato_time_api_development

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME']%>
  pool: 2
  username: <%= ENV['DATABASE_USER']%>
  password: <%= ENV['DATABASE_PASSWORD']%>
